from .domain import EventType,is_allowed_event
OFFICIAL_RECEIVING_SOURCE="DROPBOX_COMMON_SALES"
OFFICIAL_RECEIVING_SHEET="입고"
FINALIZED_SALES_SOURCE="DROPBOX_STORE_SALES"
FINALIZED_SALES_SHEET="매출"
CURRENT_SALES_SOURCE="DROPBOX_COMMON_SALES"
CURRENT_SALES_SHEET="전매장매출"

